config/routes.rb
Rails.application.routes.draw do
  root to: "users#index"

  devise_for :users

  resources :public_recipes, only: [:index]

  resources :users, only: [:index, :show] do
    resources :foods, only: [:index, :new, :create, :destroy]
    resources :recipes, only: [:index, :show, :new, :create, :destroy, :update] do
      get 'shopping_list', on: :member
      resources :recipe_foods, only: [:index, :show, :new, :create, :destroy]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :recipes, through: :recipe_foods

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :foods, through: :recipe_foods

  validates :name, presence: true
  validates :preparation_time, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :cooking_time, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :description, presence: true
  validates :public, inclusion: { in: [true, false] }
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :foods
  has_many :recipes

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @user = User.includes(:foods).find(params[:user_id])
    @food = @user.foods
  end

  def new
    @user = current_user
    @food = @user.foods.build
  end

  def create
    @food = current_user.foods.build(food_params)
    if @food.save
      redirect_to user_foods_path(current_user)
    else
      render :new
    end
  end

  def destroy
    @food = current_user.foods.find(params[:id])
    RecipeFood.where(food_id: @food.id).destroy_all
    @food.destroy
    redirect_to user_foods_path(current_user), notice: 'Food successfully deleted'
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @p_recipes = Recipe.includes([:user]).where(public: true).order(created_at: :desc)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :set_user_and_recipe

  def index
    @recipe_foods = RecipeFood.all
  end

  def show
    @recipe_foods = RecipeFood.find_by_id(params[:id])

    return unless @recipe_foods.nil?

    redirect_to recipe_foods_path
  end

  def new
    @recipe_food = RecipeFood.new
  end

  def create
    @recipe_food = @recipe.recipe_foods.build(recipe_food_params)

    if @recipe_food.save
      redirect_to user_recipe_path(@user, @recipe), notice: 'Ingredient added successfully.'
    else
      render :new
    end
  end

  def destroy
    @recipe_food = @recipe.recipe_foods.find(params[:id])
    @recipe_food.destroy
    redirect_to user_recipe_path(@user, @recipe), notice: 'Ingredient successfully deleted'
  end

  private

  def set_user_and_recipe
    @user = User.find(params[:user_id])
    @recipe = @user.recipes.find(params[:recipe_id])
  end

  def recipe_food_params
    params.require(:recipe_food).permit(:food_id, :quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @recipes = @user.recipes
  end

  def show
    @user = User.find(params[:user_id])
    @recipe = @user.recipes.find(params[:id])
    @recipe_foods = @recipe.recipe_foods.includes(:food)
  end

  def new
    @user = current_user
    @recipe = @user.recipes.build
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)
    if @recipe.save
      redirect_to user_recipes_path(current_user)
    else
      puts @recipe.errors.full_messages
      render :new
    end
  end

  def destroy
    @recipe = current_user.recipes.includes(:recipe_foods).find(params[:id])
    RecipeFood.where(recipe_id: @recipe.id).destroy_all
    @recipe.destroy

    redirect_to request.referrer, notice: 'Recipe was successfully destroyed.'
  end

  def update
    @user = User.find(params[:user_id])
    @recipe = @user.recipes.find(params[:id])

    if @recipe.update(recipe_params)
      redirect_to user_recipe_path(@user, @recipe), notice: 'Recipe was successfully updated.'
    else
      render :show
    end
  end

  def shopping_list
    @recipe = Recipe.includes([recipe_foods: [:food]]).find(params[:id])
    user_foods = current_user.foods

    missing_foods = @recipe.recipe_foods.reject { |recipe_food| user_foods.include?(recipe_food.food) }

    @data = {
      total_items: missing_foods.size,
      total_price: missing_foods.sum { |recipe_food| recipe_food.quantity * recipe_food.food.price }
    }
    @missing_foods = missing_foods
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description, :preparation_time, :cooking_time, :public)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find_by_id(params[:id])

    return unless @user.nil?

    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/index.html.erb
<h1>Foods 🍔</h1>

<div class="table-container">
  <table>
    <thead>
        <tr>
        <th>Name</th>
        <th>Measurement Unit</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <% @food.each do |food| %>
        <tr>
            <td><%= food.name %></td>
            <td><%= food.measurement_unit %></td>
            <td>$ <%= food.price %></td>
            <td><%= food.quantity %></td>
            <td><%= button_to 'Remove', user_food_path(@user, food), method: :delete%>
        </tr>
        <% end %>
    </tbody>
  </table>
  <%= link_to 'Add a food', new_user_food_path(@user), class: "add-food-link" %>
</div>

app/views/foods/new.html.erb
<h1>Add a food 🥓</h1>

<div class="form">
  <%= form_with(model: @food, url: user_foods_path(@user), local: true, method: :post) do |f| %>  <div>
    <%= f.label :name %> <br />
    <%= f.text_field :name, autocomplete: "off"%>
  </div>

  <div>
    <%= f.label :measurement_unit %> <br />
    <%= f.select :measurement_unit, ['mg', 'gr', 'kg', 'oz', 'lb', 'units'] %>
  </div>

  <div>
    <%= f.label :price %> <br />
    <%= f.number_field :price, in: 1..1000, step: 1, autocomplete: "off" %>
  </div>

  <div>
    <%= f.label :quantity %> <br />
    <%= f.number_field :quantity, in: 1..1000, step: 1, autocomplete: "off" %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipe Rails App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap">
  </head>

  <body>
    <nav class="navbar">
      <div class="nav-item">
        <% if user_signed_in? %>
          <%= link_to 'My Foods', user_foods_path(current_user) %>
          <%= link_to 'My Recipes', user_recipes_path(current_user) %>
          <%= link_to 'Public Recipes', public_recipes_path %>
        <% end %>
      </div>

      <div class="nav-item">
        <% unless current_page?(new_user_registration_path) || current_page?(new_user_session_path) %>
            <% if user_signed_in? %>
              <%= link_to 'Reset Password', edit_user_registration_path %>
              <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: "logout" %>
            <% else %>
              <%= link_to 'Sign up', new_user_registration_path %>
              <%= link_to 'Login', new_user_session_path %>
            <% end %>
        <% end %>
      </div>
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/public_recipes/index.html.erb
<div class="container">
  <h1>Public Recipes 🌐</h1>
  <table class="recipe-table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @p_recipes.each do |recipe| %>
        <tr>
          <td><%= link_to recipe.name, user_recipe_path(recipe.user, recipe) %></td>
          <td><%= truncate(recipe.description, length: 30) %></td>
          <td>
            <%= button_to "Remove", user_recipe_path(recipe.user, recipe), method: :delete,
                          disabled: recipe.user != current_user, class: "disabled" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/recipe_foods/new.html.erb
<div class="form">
  <h1>Add the Ingredients of recipe</h1>
  <%= form_with(model: [@user, @recipe, @recipe_food], url: user_recipe_recipe_foods_path(@user, @recipe), local: true, method: :post) do |f| %>
    <div class="food">
      <%= f.label :food_id %> :
      <%= f.collection_select :food_id, Food.all, :id, :name %>
    </div>

    <div class="food">
      <%= f.label :quantity %> :
      <%= f.number_field :quantity, in: 1..1000, step: 1, autocomplete: "off" %>
    </div>

    <div>
      <%= f.submit "Add Ingredient" %>
    </div>
  <% end %>
</div>

app/views/recipes/index.html.erb
<div class="container">
  <h1>Recipes 🍲</h1>
  <table class="recipe-table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @recipes.each do |recipe| %>
        <tr>
          <td><%= link_to recipe.name, user_recipe_path(@user, recipe) %></td>
          <td><%= truncate(recipe.description, length: 30) %></td>
          <td><%= button_to "Remove", user_recipe_path(@user, recipe), method: :delete %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to "New Recipe", new_user_recipe_path(@user), class: "add-food-link" %>
</div>

app/views/recipes/new.html.erb
<h1>Create your recipe📝😍</h1>

<div class="form">
  <%= form_with(model: @recipe, url: user_recipes_path(@user), local: true, method: :post) do |f| %>  <div>
    <%= f.label :name %> <br />
    <%= f.text_field :name, autocomplete: "off" %>
  </div>

  <div>
    <%= f.label :description %> <br />
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.label :preparation_time %> <br />
    <%= f.number_field :preparation_time, in: 1..1000, step: 1, autocomplete: "off" %>
  </div>

  <div>
    <%= f.label :cooking_time %> <br />
    <%= f.number_field :cooking_time, in: 1..1000, step: 1, autocomplete: "off" %>
  </div>

  <div>
    <%= f.label :public %>
    <%= f.check_box :public %>

  <div>
    <%= f.submit class: "button" %>
  </div>
<% end %>
</div>

app/views/recipes/shopping_list.html.erb
<h1><%= @recipe.name %> Shopping List</h1>

<div class="container">
  <% if @data[:total_items] == 0 %> 
    <div class="shopping">
      <h3>You have all the ingredients you need!</h3>
    </div>
  <% else %>
    <div class="shopping">
      <h3>Total food items: <%= @data[:total_items] %></h3>
      <h3>Total price: $<%= @data[:total_price] %></h3>
    </div>
    <div class="table-container">
      <table>
        <thead>
            <tr>
              <th>Food</th>
              <th>Quantity</th>
              <th>Price</th>
            </tr>
        </thead>
        <tbody>
          <% @missing_foods.each do |missing| %>
            <tr>
              <td><%= missing.food.name %> </td>
              <td><%= missing.quantity %> <%= missing.food.measurement_unit %> </td>
              <td>$ <%= missing.food.price * missing.quantity %> </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
</div>

app/views/recipes/show.html.erb
<div class="container">
  <h1><%= @recipe.name %> 📝</h1>
  <div class="genral-detal">
    <div class="details">
      <h3>Preparation time: <%= @recipe.preparation_time %></h3>
      <h3>Cooking time: <%= @recipe.cooking_time %></h3>
      <h3><%= @recipe.description %></h3>
    </div>
    <div>
      <%= form_with(model: @recipe, url: user_recipe_path(@user, @recipe), local: true, method: :patch) do |f| %>
        <div>
          <p><%= f.label :public %>
            <label class="switch">
              <%= f.hidden_field :public, value: false %>
              <%= f.check_box :public, { onchange: 'this.form.submit()', 
                                        disabled: @user != current_user }, true, false %>
              <span class="slider"></span>
            </label>
          </p>
        </div>
      <% end %>
    </div>
  </div>

  <div class="btns">
    <%= button_to "Generate Shopping List", shopping_list_user_recipe_path(@user, @recipe), method: :get, class: "add-food-link"%>
    <%= button_to "Add ingredients", new_user_recipe_recipe_food_path(@user, @recipe), class: "add-food-link", 
                  method: :get, disabled: @recipe.user != current_user  %>
  </div>

  <div>
    <table>
      <thead>
          <tr>
            <th>Food</th>
            <th>Quantity</th>
            <th>Value</th>
            <th>Actions</th>
          </tr>
      </thead>
      <tbody>    
        <% @recipe_foods.each do |recipe_food| %>
          <tr>
              <td><%= recipe_food.food.name %></td>
              <td><%= recipe_food.quantity %> <%= recipe_food.food.measurement_unit %> </td>
              <td>$ <%= recipe_food.food.price * recipe_food.quantity %></td>
              <td><%= button_to 'Remove', user_recipe_recipe_food_path(@user, @recipe, recipe_food), method: :delete, disabled: @user != current_user %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/index.html.erb
<div class="img">
    <div class="welcome">Welcome to our Recipe App Dear:
        <% if user_signed_in? %>
            <%= current_user.name %> 👋😊
        <% end %>
    </div>
</div>